# Generated by Django 5.1.1 on 2024-09-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone_offset', models.CharField(max_length=10)),
                ('timezone_description', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('registered', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('cell', models.CharField(max_length=20)),
                ('picture_large', models.URLField(max_length=255)),
                ('picture_medium', models.URLField(max_length=255)),
                ('picture_thumbnail', models.URLField(max_length=255)),
            ],
        ),
    ]
